// Generated by CoffeeScript 1.6.2
(function() {
  var testCurrent, testWithBrowser, _ref;

  _ref = require('../common/basic-test-base'), testWithBrowser = _ref.testWithBrowser, testCurrent = _ref.testCurrent;

  describe("wd-sync", function() {
    return describe("headless", function() {
      var browserName, _i, _len, _ref1;

      _ref1 = [void 0, 'zombie'];
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        browserName = _ref1[_i];
        testWithBrowser({
          type: 'headless',
          desired: {
            browserName: browserName
          }
        });
      }
      return testCurrent({
        type: 'headless',
        desired: {
          browserName: 'chrome'
        }
      });
    });
  });

}).call(this);
