// Generated by CoffeeScript 1.3.3
(function() {
  var testCurrent, testWithBrowser, _ref;

  _ref = require('../common/basic-test-base'), testWithBrowser = _ref.testWithBrowser, testCurrent = _ref.testCurrent;

  describe("wd-sync", function() {
    return describe("headless", function() {
      return describe("basic tests", function() {
        describe("browsing", function() {
          var browserName, _i, _len, _ref1, _results;
          _ref1 = [void 0, 'zombie'];
          _results = [];
          for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
            browserName = _ref1[_i];
            _results.push(testWithBrowser('headless', browserName));
          }
          return _results;
        });
        return describe("ws.current()", function() {
          return testCurrent('headless');
        });
      });
    });
  });

}).call(this);
