// Generated by CoffeeScript 1.3.3
(function() {
  var f;

  f = function() {
    before(function(done) {
      console.log("before");
      return done(null);
    });
    after(function(done) {
      console.log("after");
      return done(null);
    });
    describe("experiment 1", function() {
      return it("should work", function(done) {
        return done(null);
      });
    });
    return describe("experiment 2", function() {
      return it("should work", function(done) {
        return done(null);
      });
    });
  };

  describe("experiment", function() {
    return f();
  });

}).call(this);
