// Generated by CoffeeScript 1.3.3
(function() {
  var test;

  test = require('../common/typing-test-base').test;

  describe("wd-sync", function() {
    return describe("headless", function() {
      return test('headless', 'zombie');
    });
  });

}).call(this);
