// Generated by CoffeeScript 1.6.2
(function() {
  var Express, test, _ref;

  _ref = require('../common/methods-test-base'), test = _ref.test, Express = _ref.Express;

  describe("wd-sync", function() {
    return describe("local", function() {
      var express;

      express = new Express;
      before(function(done) {
        express.start(done);
        return done(null);
      });
      after(function(done) {
        express.stop(done);
        return done(null);
      });
      return test('remote', 'firefox');
    });
  });

}).call(this);
